
version: '3.8'  
services:
  postgres:
    image: postgres:latest
    container_name: drone-postgres
    restart: always
    ports:
      - '5432:5432'  
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=Drones
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gitlab-network

networks:
  gitlab-network:
    driver: bridge

volumes:
  postgres_data:
